distributed.worker - WARNING - Compute Failed
Function:  f
args:      (['1979-02-01 00:00:00', '1979-02-01 03:00:00', '1979-02-01 06:00:00', '1979-02-01 09:00:00', '1979-02-01 12:00:00', '1979-02-01 15:00:00', '1979-02-01 18:00:00', '1979-02-01 21:00:00', '1979-02-02 00:00:00', '1979-02-02 03:00:00'], [(-16.6, 170.08), (-16.8519, 170.233), (-17.165, 170.438), (-17.5502, 170.665), (-18.0, 170.9), (-18.4747, 171.114), (-19.0051, 171.323), (-19.5955, 171.535), (-20.22, 171.74), (-20.7863, 171.955)])
kwargs:    {}
Exception: 'AttributeError("\'NoneType\' object has no attribute \'sel\'")'

Traceback (most recent call last):
  File "/home/156/jm0124/dl-cyclones/reanalysis/test_for_cpu.py", line 68, in <module>
    get_some_cyclones_list(cyclones)
  File "/home/156/jm0124/dl-cyclones/reanalysis/test_for_cpu.py", line 62, in get_some_cyclones_list
    job(list_of_tracks[n])
  File "/home/156/jm0124/dl-cyclones/reanalysis/test_for_cpu.py", line 46, in job
    cyclone = xarray.concat(chunks, "time").to_numpy()
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/xarray/core/concat.py", line 220, in concat
    first_obj, objs = utils.peek_at(objs)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/xarray/core/utils.py", line 193, in peek_at
    gen = iter(iterable)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/dask/bag/core.py", line 1470, in __iter__
    return iter(self.compute())
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/dask/base.py", line 290, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/dask/base.py", line 573, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/distributed/client.py", line 3010, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/distributed/client.py", line 2162, in gather
    return self.sync(
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/distributed/utils.py", line 311, in sync
    return sync(
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/distributed/utils.py", line 378, in sync
    raise exc.with_traceback(tb)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/distributed/utils.py", line 351, in f
    result = yield future
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/distributed/client.py", line 2025, in _gather
    raise exception.with_traceback(traceback)
  File "/home/156/jm0124/dl-cyclones/reanalysis/test_for_cpu.py", line 39, in f
    return lib.track_to_ndarray_xr(
  File "/home/156/jm0124/dl-cyclones/reanalysis/track_to_ndarray.py", line 104, in track_to_ndarray_xr
    res.append(sample_window(ds.sel(time=time), degree_window, lat, lon))
AttributeError: 'NoneType' object has no attribute 'sel'
distributed.nanny - WARNING - Worker process still alive after 3.9999990463256836 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3.9999994277954105 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3.999999237060547 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3.9999994277954105 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3.9999994277954105 seconds, killing
distributed.worker - WARNING - Compute Failed
Function:  f
args:      (['1979-02-01 00:00:00', '1979-02-01 03:00:00', '1979-02-01 06:00:00', '1979-02-01 09:00:00', '1979-02-01 12:00:00', '1979-02-01 15:00:00', '1979-02-01 18:00:00', '1979-02-01 21:00:00', '1979-02-02 00:00:00', '1979-02-02 03:00:00'], [(-16.6, 170.08), (-16.8519, 170.233), (-17.165, 170.438), (-17.5502, 170.665), (-18.0, 170.9), (-18.4747, 171.114), (-19.0051, 171.323), (-19.5955, 171.535), (-20.22, 171.74), (-20.7863, 171.955)])
kwargs:    {}
Exception: 'AttributeError("\'NoneType\' object has no attribute \'sel\'")'

Traceback (most recent call last):
  File "/home/156/jm0124/dl-cyclones/reanalysis/test_for_cpu.py", line 68, in <module>
    get_some_cyclones_list(cyclones)
  File "/home/156/jm0124/dl-cyclones/reanalysis/test_for_cpu.py", line 62, in get_some_cyclones_list
    job(list_of_tracks[n])
  File "/home/156/jm0124/dl-cyclones/reanalysis/test_for_cpu.py", line 46, in job
    cyclone = xarray.concat(chunks, "time").to_numpy()
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/xarray/core/concat.py", line 220, in concat
    first_obj, objs = utils.peek_at(objs)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/xarray/core/utils.py", line 193, in peek_at
    gen = iter(iterable)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/dask/bag/core.py", line 1470, in __iter__
    return iter(self.compute())
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/dask/base.py", line 290, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/dask/base.py", line 573, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/distributed/client.py", line 3010, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/distributed/client.py", line 2162, in gather
    return self.sync(
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/distributed/utils.py", line 311, in sync
    return sync(
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/distributed/utils.py", line 378, in sync
    raise exc.with_traceback(tb)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/distributed/utils.py", line 351, in f
    result = yield future
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/distributed/client.py", line 2025, in _gather
    raise exception.with_traceback(traceback)
  File "/home/156/jm0124/dl-cyclones/reanalysis/test_for_cpu.py", line 39, in f
    return lib.track_to_ndarray_xr(
  File "/home/156/jm0124/dl-cyclones/reanalysis/track_to_ndarray.py", line 104, in track_to_ndarray_xr
    res.append(sample_window(ds.sel(time=time), degree_window, lat, lon))
AttributeError: 'NoneType' object has no attribute 'sel'
distributed.nanny - WARNING - Worker process still alive after 3.999999237060547 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3.9999996185302735 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3.999999237060547 seconds, killing
